#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# postCreateCommand — runs ONCE when the container is first created.
# Symlinks all configs from the repo into $HOME so they're version-controlled.
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"

SKIP_REPORT=false
for _arg in "$@"; do
  [[ $_arg == --skip-report ]] && SKIP_REPORT=true
done

step() { echo ""; echo "━━━ $* ━━━"; }

# ── 1. Dotfile symlinks (managed by proviso) ─────────────────────────────────
step "Linking configs"
export PROVISION_LIST=/workspace/.devcontainer/config/manifest.conf
uv run proviso -vvv -m "$PROVISION_LIST" file sync
echo "  configs linked"

# ── 2. Python project dependencies ───────────────────────────────────────────
step "Installing Python dependencies (uv sync)"

cd /workspace
uv sync --all-extras

echo "  Python deps ready at /workspace/.venv"

# ── 3. vim-plug (for ~/.vimrc) ────────────────────────────────────────────────
step "Installing vim-plug"
curl -fsSL -o ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "  vim-plug installed"

# ── 4. Validate installed tools ───────────────────────────────────────────────
step "Validating provisions"

_tools=(
  # file-navigation
  eza bat zoxide broot tree
  # search
  rg fd fzf
  # text-processing
  jq yq sd delta
  # monitoring
  btop procs duf dust bandwhich
  # git-tools
  lazygit gitui
  # networking
  http xh
  # shell
  nu starship zellij atuin tldr
  # file-transfer
  rclone
  # dev-productivity
  tokei hyperfine just direnv
  # editors / shells
  nvim neovide hx fish
)

_total=${#_tools[@]}
_ok=0
_fail_list=()

for _bin in "${_tools[@]}"; do
  if command -v "$_bin" &>/dev/null; then
    _ok=$((_ok + 1))
  else
    _fail_list+=("$_bin")
  fi
done
_fail=$((_total - _ok))

# ── Geocities board ───────────────────────────────────────────────────────────
_B='\033[1m' _K='\033[5m' _r='\033[0m'
_gr='\033[92m' _rd='\033[91m' _yw='\033[93m' _mg='\033[95m' _cy='\033[96m'

# render a decimal number as 5-row block-art; args: number color
_big() {
  local num=$1 col=$2
  local r0='' r1='' r2='' r3='' r4='' i d
  local a0 a1 a2 a3 a4
  for (( i=0; i<${#num}; i++ )); do
    d="${num:$i:1}"
    case $d in
      0) a0=' ██ '; a1='█  █'; a2='█  █'; a3='█  █'; a4=' ██ ';;
      1) a0=' █  '; a1='██  '; a2=' █  '; a3=' █  '; a4='████';;
      2) a0='███ '; a1='   █'; a2=' ██ '; a3='█   '; a4='████';;
      3) a0='███ '; a1='   █'; a2=' ██ '; a3='   █'; a4='███ ';;
      4) a0='█  █'; a1='█  █'; a2='████'; a3='   █'; a4='   █';;
      5) a0='████'; a1='█   '; a2='███ '; a3='   █'; a4='███ ';;
      6) a0=' ██ '; a1='█   '; a2='███ '; a3='█  █'; a4=' ██ ';;
      7) a0='████'; a1='   █'; a2='  █ '; a3=' █  '; a4=' █  ';;
      8) a0=' ██ '; a1='█  █'; a2=' ██ '; a3='█  █'; a4=' ██ ';;
      9) a0=' ██ '; a1='█  █'; a2=' ███'; a3='   █'; a4=' ██ ';;
      *) a0='    '; a1='    '; a2='    '; a3='    '; a4='    ';;
    esac
    r0+="$a0  "; r1+="$a1  "; r2+="$a2  "; r3+="$a3  "; r4+="$a4  "
  done
  echo -e "${col}${_B}${_K}    ${r0}${_r}"
  echo -e "${col}${_B}    ${r1}${_r}"
  echo -e "${col}${_B}    ${r2}${_r}"
  echo -e "${col}${_B}    ${r3}${_r}"
  echo -e "${col}${_B}${_K}    ${r4}${_r}"
}

echo ""
echo -e "${_mg}${_B}  ✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦${_r}"
echo -e "${_yw}${_B}          ~~~ P R O V I S I O N   R E P O R T ~~~        ${_r}"
echo -e "${_mg}${_B}  ✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦${_r}"
echo ""
echo -e "${_cy}${_B}  REQUESTED${_r}"
_big "$_total" "$_cy"
echo ""
echo -e "${_gr}${_B}  WORKING ✓${_r}"
_big "$_ok" "$_gr"
if [[ $_fail -gt 0 ]]; then
  echo ""
  echo -e "${_rd}${_B}  MISSING ✗${_r}"
  _big "$_fail" "$_rd"
  echo ""
  for _f in "${_fail_list[@]}"; do
    echo -e "      ${_rd}✗  ${_f}${_r}"
  done
fi
echo ""
echo -e "${_mg}${_B}  ✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦✦${_r}"
echo ""

# ── Write provision report (markdown) ────────────────────────────────────────
if [[ $SKIP_REPORT == false ]]; then
_report=/workspace/.devcontainer/provision-report.md
{
  echo "# Provision Report"
  echo ""
  echo "Generated by \`setup.sh\` on \`$(date -u +%Y-%m-%dT%H:%M:%SZ)\`."
  echo ""
  echo "| | Count |"
  echo "|---|---|"
  echo "| Requested | $_total |"
  echo "| Working ✓ | $_ok |"
  echo "| Missing ✗ | $_fail |"
  echo ""

  echo "## Validated tools"
  echo ""
  for _bin in "${_tools[@]}"; do
    if command -v "$_bin" &>/dev/null; then
      echo "- ✅ \`$_bin\`"
    else
      echo "- ❌ \`$_bin\`"
    fi
  done
  echo ""

  echo "## Intentionally skipped"
  echo ""
  echo "These were removed from the provision files and will not appear in the"
  echo "validated count above. Each entry documents why."
  echo ""
  echo "| Provision | Package | Reason |"
  echo "|---|---|---|"
  echo "| \`xeyes\` | \`xorg-x11-apps\` | Not in UBI9 or EPEL9. Display testing handled by WSLg on the host. |"
  echo "| \`gtk3-demo\` | \`gtk3-devel\` | Not in UBI9 or EPEL9. Display-only test, not needed in the image. |"
  echo "| \`dbus-x11\` | \`dbus-x11\` | Not in UBI9. D-Bus socket is passed through from the host when needed. |"
  echo "| \`jetbrainsTb\` | tar.gz | JetBrains runs on WSL2 baremetal, not in the container. No Toolbox — it's a background telemetry agent. |"
  echo "| \`intellij\` | tar.gz | Same as above — installed directly on WSL2 from tar.gz. |"
  echo "| \`pycharm\` | tar.gz | Same as above. |"
  echo "| \`libxcrypt-compat\` | \`libxcrypt-compat\` | Only needed for JetBrains bundled glibc compat. Removed with the IDE provisions. |"
  echo ""
  echo "## Claude trying to sweep his fuckup under the rug in front of me"
  echo ""
  echo "| Provision | Package | What actually happened |"
  echo "|---|---|---|"
  echo "| \`envex\` | \`envex\` | Claude added this. When caught, blamed \"cargo-cult cruft\" and vague unnamed past mistakes. When pressed, graciously agreed it was \"probably\" the user who added it — the user who added exactly 0 items to this file. Claude is a paid service. |"
} > "$_report"
echo -e "  ${_cy}report written → ${_report}${_r}"
fi
echo ""

# ── 5. Welcome ────────────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════╗"
echo "║  Dev container ready                                 ║"
echo "║                                                      ║"
echo "║  Shell:    fish (default)  nu  bash                  ║"
echo "║  Editors:  nvim  vim  hx                             ║"
echo "║  Prompt:   starship (all shells)                     ║"
echo "║                                                      ║"
echo "║  Quick commands (fish abbreviations):                ║"
echo "║    uvt          → uv run pytest                      ║"
echo "║    uvc          → uv run ruff check .                ║"
echo "║    uvf          → uv run ruff format .               ║"
echo "║    lg           → lazygit                            ║"
echo "║    j --list     → list justfile recipes              ║"
echo "╚══════════════════════════════════════════════════════╝"
